// Curated list of popular Taiwan-equity funds for the "全部" ranking board.
// Generated by scripts/select-curated.mjs; edit freely.
export const CURATED_FUNDS = [
  {
    "code": "AC0050",
    "name": "元大台灣卓越50基金"
  },
  {
    "code": "AC0055",
    "name": "元大台灣金融基金"
  },
  {
    "code": "AC0057",
    "name": "富邦台灣摩根基金"
  },
  {
    "code": "AC0053",
    "name": "元大台灣電子科技基金"
  },
  {
    "code": "ACCB78",
    "name": "合庫台灣高科技基金"
  },
  {
    "code": "ACFH03",
    "name": "復華高成長基金"
  },
  {
    "code": "ACKH321",
    "name": "野村優質基金"
  },
  {
    "code": "ACYT09",
    "name": "元大高科技基金"
  },
  {
    "code": "ACCA319",
    "name": "群益馬拉松基金"
  },
  {
    "code": "ACCJ84",
    "name": "匯豐台灣精典基金"
  },
  {
    "code": "ACPS06",
    "name": "統一中小基金"
  },
  {
    "code": "AC0051",
    "name": "元大台灣中型100基金"
  },
  {
    "code": "ACFH06",
    "name": "復華數位經濟基金"
  },
  {
    "code": "ACML05",
    "name": "玉山店頭市場基金"
  },
  {
    "code": "ACPS10",
    "name": "統一奔騰基金"
  },
  {
    "code": "ACCA274",
    "name": "群益店頭市場基金"
  },
  {
    "code": "ACYT11",
    "name": "元大新主流基金"
  },
  {
    "code": "ACCB157",
    "name": "合庫台灣基金"
  },
  {
    "code": "ACAI479",
    "name": "柏瑞巨人基金"
  },
  {
    "code": "ACCT01",
    "name": "富邦台灣心基金"
  },
  {
    "code": "ACJS73",
    "name": "富邦台灣永續成長股息基金"
  },
  {
    "code": "ACFT12",
    "name": "富蘭克林華美高科技基金"
  },
  {
    "code": "ACES125",
    "name": "施羅德台灣樂活中小基金"
  },
  {
    "code": "ACKH07",
    "name": "野村積極成長基金"
  },
  {
    "code": "ACCH01",
    "name": "街口台灣基金"
  },
  {
    "code": "ACJS06",
    "name": "富邦精選五虎基金"
  },
  {
    "code": "ACDF0701",
    "name": "台中銀數位時代基金"
  },
  {
    "code": "ACFP11",
    "name": "富邦科技基金"
  },
  {
    "code": "ACCH03",
    "name": "街口中小型基金"
  },
  {
    "code": "ACAP96",
    "name": "宏利台灣動力基金"
  },
  {
    "code": "ACFP10",
    "name": "富邦高成長基金"
  },
  {
    "code": "ACKH322",
    "name": "野村高科技基金"
  },
  {
    "code": "ACML07",
    "name": "玉山科技島基金"
  },
  {
    "code": "ACTS09",
    "name": "新光創新科技基金"
  },
  {
    "code": "ACDD102",
    "name": "安聯台灣大壩基金"
  },
  {
    "code": "ACJS07",
    "name": "富邦高科技基金"
  },
  {
    "code": "ACML124",
    "name": "玉山高成長基金"
  },
  {
    "code": "ACTS10",
    "name": "新光店頭基金"
  },
  {
    "code": "ACNC16",
    "name": "第一金電子基金"
  },
  {
    "code": "ACIC06",
    "name": "野村e科技基金"
  }
];
