// One-off: pick ~40 popular Taiwan-equity funds for the "全部" ranking board.
// Strategy: from the full index, drop obvious non-TW-equity funds by name, test a
// candidate set against the real estimator, and keep those with good TW coverage.
import fs from 'node:fs/promises';
import { computeMany } from '../server/estimate.js';

const idx = JSON.parse(await fs.readFile('data/fund-index.json', 'utf8')).funds;

const EXCLUDE = /全球|美國|美股|歐洲|日本|中國|大陸|亞洲|新興|印度|越南|東協|世界|國際|海外|債|貨幣|平衡|組合|收益|多重|資產|房地產|REIT|黃金|能源|生技醫療基金|貨幣市場|傘型|ETF|指數|成分|槓桿|反向|美元|人民幣|南非|拉丁|新興市場/;
const INCLUDE = /台|科技|中小|成長|價值|精選|卓越|龍頭|旗艦|馬拉松|黑馬|大滿貫|奔騰|店頭|高股息|金鑽|創新|智慧|數位|主流|核心|動力|富貴|小龍|金融|電子|通訊|建設|精華|鴻運|新機會|target|target/;

// Collapse share classes: everything up to and including 基金 is the base fund.
const baseName = (n) => { const i = n.indexOf('基金'); return i >= 0 ? n.slice(0, i + 2) : n.replace(/[-(（].*$/, ''); };

const byBase = new Map();
for (const f of idx) {
  if (EXCLUDE.test(f.name) || !INCLUDE.test(f.name)) continue;
  const b = baseName(f.name);
  const cur = byBase.get(b);
  if (!cur || f.name.length < cur.name.length) byBase.set(b, { code: f.code, name: b });
}
const candidates = [...byBase.values()].slice(0, 130);

console.log('distinct candidates:', candidates.length);
const results = await computeMany(candidates.map((c) => c.code), { withNav: false });
const nameByCode = new Map(candidates.map((c) => [c.code, c.name]));

const good = results
  .filter((r) => r.estimatedMovePct != null && r.disclosedWeight >= 25 && r.coveragePct >= 60)
  .sort((a, b) => b.disclosedWeight - a.disclosedWeight)
  .slice(0, 40)
  .map((r) => ({ code: r.code, name: nameByCode.get(r.code) || r.name }));

console.log('selected:', good.length);
const file =
  `// Curated list of popular Taiwan-equity funds for the "全部" ranking board.\n` +
  `// Generated by scripts/select-curated.mjs; edit freely.\n` +
  `export const CURATED_FUNDS = ${JSON.stringify(good, null, 2)};\n`;
await fs.writeFile('server/curated.js', file, 'utf8');
console.log(good.map((g) => `${g.code} ${g.name}`).join('\n'));
